#apiVersion: v1
#kind: Namespace
#metadata:
#  name: dev
#---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myweb
  namespace: default
spec:
  strategy:
    rollingUpdate:
      maxSurge: 10%
      maxUnavailable: 0
  replicas: 1
  selector:
    matchLabels:
      app: myweb
  template:
    metadata:
      labels:
        app: myweb
    spec:
      containers:
        - name: myweb
          image: registry.cn-hangzhou.aliyuncs.com/godemo/myweb:latest
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 300m
              memory: 200Mi
      imagePullSecrets:
        - name: regsecret
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: myweb
  name: myweb
  namespace: default
spec:
  ports:
    - port: 8888
      targetPort: 8888
  selector:
    app: myweb
  type: ClusterIP
