name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: build docker
        run: |
          export VERSION=$(date +%s)
          docker login --username=yj19931029 --password=${{ secrets.REGISTRYPASSWORD }} registry.cn-hangzhou.aliyuncs.com
          docker build . --file Dockerfile --tag myweb:$VERSION
          docker tag $(docker images |  grep myweb | awk '{print $3}') registry.cn-hangzhou.aliyuncs.com/godemo/myweb:latest
          docker push registry.cn-hangzhou.aliyuncs.com/godemo/myweb:latest
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: cd /root/learn/myweb && kubectl apply -f myweb.yaml
